# Generated by Skyramp v1.3.27 on 2026-06-15 10:59:13.17280405 +0000 UTC m=+388.624372356
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output meal_hierarchy_ownership_verification_integration_test.py \
# 		--output-dir /home/runner/work/wger-testb/wger-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger-testb/wger-testb/tests/skyramp/scenario_meal-hierarchy-ownership-verification.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8091")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    plan = "1"

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "description": "Plan-1750000000",
        "only_logging": false
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/nutritionplan/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "description") == "Plan-1750000000"
    assert skyramp.get_response_value(endpoint_3_POST_response, "only_logging") == False
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Breakfast-1750000000",
        "plan": 1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/meal/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"plan": plan}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Breakfast-1750000000"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "plan") == skyramp.get_response_value(endpoint_3_POST_response, "id")

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/meal/{meal}/",
        method="GET",
        headers=headers,
        path_params={"meal": plan}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_2_GET_response, "name") == "Breakfast-1750000000"
    assert skyramp.get_response_value(endpoint_2_GET_response, "plan") == skyramp.get_response_value(endpoint_3_POST_response, "id")


if __name__ == "__main__":
    test_integration()
