# Generated by Skyramp v1.3.27 on 2026-06-15 10:56:28.42745389 +0000 UTC m=+264.020884973
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output measurement_category_name_list_integration_test.py \
# 		--output-dir /home/runner/work/wger-testb/wger-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger-testb/wger-testb/tests/skyramp/scenario_measurement-category-name-list.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8091")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "WaistLine-1718413200",
        "unit": "cm"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement-category/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "WaistLine-1718413200"
    assert skyramp.get_response_value(endpoint_1_POST_response, "unit") == "cm"

    category_id = skyramp.get_response_value(endpoint_1_POST_response, "id")
    # Request Body
    endpoint_2_POST_request_body = '{{"category": {cat}, "date": "2024-01-16T10:00:00Z", "value": "80.00"}}'.format(cat=category_id)
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") > 0
    assert float(skyramp.get_response_value(endpoint_2_POST_response, "value")) == 80.0
    assert skyramp.get_response_value(endpoint_2_POST_response, "category_name") == "WaistLine-1718413200"
    assert skyramp.get_response_value(endpoint_2_POST_response, "category") == skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement/",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "count") >= 1
    assert skyramp.get_response_value(endpoint_2_GET_response, "results.0.id") > 0
    assert skyramp.get_response_value(endpoint_2_GET_response, "results.0.category_name") is not None


if __name__ == "__main__":
    test_integration()
