# Generated by Skyramp v1.3.27 on 2026-06-15 10:59:10.951869055 +0000 UTC m=+386.403437344
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output measurement_ownership_create_verification_integration_test.py \
# 		--output-dir /home/runner/work/wger-testb/wger-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger-testb/wger-testb/tests/skyramp/scenario_measurement-ownership-create-verification.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8091")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    measurement = "1"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Weight-1750000000",
        "unit": "kg"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement-category/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Weight-1750000000"
    assert skyramp.get_response_value(endpoint_1_POST_response, "unit") == "kg"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "category": 1,
        "date": "2026-06-15",
        "value": 75.5
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "date").startswith("2026-06-15")
    assert float(skyramp.get_response_value(endpoint_2_POST_response, "value")) == 75.5
    assert float(skyramp.get_response_value(endpoint_2_POST_response, "value")) >= 0
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_2_POST_response, "category") == skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement/{measurement}/",
        method="GET",
        headers=headers,
        path_params={"measurement": measurement}
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_3_GET_response, "id") == skyramp.get_response_value(endpoint_2_POST_response, "id")
    assert skyramp.get_response_value(endpoint_3_GET_response, "date").startswith("2026-06-15")
    assert float(skyramp.get_response_value(endpoint_3_GET_response, "value")) == 75.5
    assert skyramp.get_response_value(endpoint_3_GET_response, "category") == skyramp.get_response_value(endpoint_1_POST_response, "id")


if __name__ == "__main__":
    test_integration()
