# Generated by Skyramp v1.3.27 on 2026-06-15 10:56:25.74252666 +0000 UTC m=+261.335957742
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output measurement_category_name_detail_integration_test.py \
# 		--output-dir /home/runner/work/wger-testb/wger-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger-testb/wger-testb/tests/skyramp/scenario_measurement-category-name-detail.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8091")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    measurement = "1"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "BicepsSize-1718413200",
        "unit": "cm"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement-category/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "BicepsSize-1718413200"
    assert skyramp.get_response_value(endpoint_1_POST_response, "unit") == "cm"

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "category": 1,
        "date": "2024-01-15T10:00:00Z",
        "notes": "test note",
        "value": "35.50"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_2_POST_response, "notes") == "test note"
    assert float(skyramp.get_response_value(endpoint_2_POST_response, "value")) == 35.5
    assert skyramp.get_response_value(endpoint_2_POST_response, "category_name") == "BicepsSize-1718413200"
    assert skyramp.get_response_value(endpoint_2_POST_response, "category") == skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement/{measurement}/",
        method="GET",
        headers=headers,
        path_params={"measurement": measurement}
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_3_GET_response, "id") == skyramp.get_response_value(endpoint_2_POST_response, "id")
    assert skyramp.get_response_value(endpoint_3_GET_response, "category_name") == "BicepsSize-1718413200"
    assert float(skyramp.get_response_value(endpoint_3_GET_response, "value")) == 35.5
    assert skyramp.get_response_value(endpoint_3_GET_response, "notes") == "test note"
    assert skyramp.get_response_value(endpoint_3_GET_response, "category") == skyramp.get_response_value(endpoint_1_POST_response, "id")


if __name__ == "__main__":
    test_integration()
