# Generated by Skyramp v1.3.27 on 2026-06-15 10:56:00.020831241 +0000 UTC m=+235.614262325
# Command: skyramp generate contract rest http://localhost:8091/api/v2/measurement/ \
# 		--api-schema http://localhost:8091/api/v2/schema?format=json \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output measurement_contract_test.py \
# 		--output-dir /home/runner/work/wger-testb/wger-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8091")

# contract test for /api/v2/measurement/ GET
def test_measurement_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_measurement_GET_response_body = r'''{
        "count": 123,
        "results": [
            {
                "category": 1,
                "category_name": "BicepsSize",
                "id": 1,
                "value": 35.5
            }
        ]
    }'''

    # Execute Request
    measurement_GET_response = client.send_request(
        url=URL,
        path="/api/v2/measurement/",
        method="GET",
        headers=headers,
        query_params={
            "limit": 20,
            "offset": 0
        }
    )

    # Generated Assertions
    assert measurement_GET_response.status_code == 200
    assert skyramp.check_schema(measurement_GET_response, expected_measurement_GET_response_body)
    assert skyramp.get_response_value(measurement_GET_response, "count") is not None
    assert skyramp.get_response_value(measurement_GET_response, "results.0.category") is not None
    assert skyramp.get_response_value(measurement_GET_response, "results.0.category_name") is not None
    assert skyramp.get_response_value(measurement_GET_response, "count") >= 0
    assert skyramp.get_response_value(measurement_GET_response, "results.0.id") > 0
    assert float(skyramp.get_response_value(measurement_GET_response, "results.0.value")) >= 0


if __name__ == "__main__":
    test_measurement_get()
