# Generated by Skyramp v1.3.27 on 2026-06-15 10:55:57.965176535 +0000 UTC m=+235.598988072
# Command: skyramp generate contract rest http://localhost:8091/api/v2/weightentry/summary/ \
# 		--api-schema http://localhost:8091/api/v2/schema?format=json \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output weightentry_summary_contract_test.py \
# 		--output-dir /home/runner/work/wger-testb/wger-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8091")

# contract test for /api/v2/weightentry/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_summary_GET_response_body = r'''{
        "count": 1,
        "min_weight": 75.0,
        "max_weight": 85.0,
        "avg_weight": 80.0
    }'''

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/v2/weightentry/summary/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert summary_GET_response.status_code == 200
    assert skyramp.check_schema(summary_GET_response, expected_summary_GET_response_body)
    assert skyramp.get_response_value(summary_GET_response, "count") is not None
    assert skyramp.get_response_value(summary_GET_response, "count") >= 0


if __name__ == "__main__":
    test_summary_get()
