# Generated by Skyramp v1.3.27 on 2026-06-15 10:55:21.859407739 +0000 UTC m=+159.326466617
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output weightentry_year_filter_isolation_integration_test.py \
# 		--output-dir /home/runner/work/wger-testb/wger-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger-testb/wger-testb/tests/skyramp/scenario_weightentry-year-filter-isolation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8091")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "date": "2024-03-15T10:00:00",
        "weight": "75.50"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "75.50"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "date") is not None

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "date": "2025-06-20T10:00:00",
        "weight": "80.00"
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "weight") == "80.00"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "id") > 0

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="GET",
        headers=headers,
        query_params={"year": ["2024"]}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.weight") == "75.50"
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.date") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.1") is None


if __name__ == "__main__":
    test_integration()
